### ISSUE TITLE
NullPointerException when calling deserialiser

### ISSUE THREAD

**Issue by muffix** [OpenTSDB/opentsdb-rpc-kafka#10]
I've had some trouble getting this plugin to run and was facing a NullPointerException when it reads the first message. 

```
2018-12-05 10:30:16,185 ERROR [histograms_0_314c7ab81c1d] KafkaRpcPluginThread: Exception in kafkaReader or Tsdb Writer
java.lang.NullPointerException: null
	at net.opentsdb.tsd.KafkaRpcPluginThread.run(KafkaRpcPluginThread.java:284) ~[opentsdb-rpc-kafka-0.1.0-all.jar:]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

When a new consumer group is created, that group instantiates the specified deserialiser and creates the plugin thread. In its constructor, the thread then goes and [gets the deserialiser](https://github.com/OpenTSDB/opentsdb-rpc-kafka/blob/master/src/main/java/net/opentsdb/tsd/KafkaRpcPluginThread.java#L190) from the consumer group. 
However, since the consumer group [first starts the thread](https://github.com/OpenTSDB/opentsdb-rpc-kafka/blob/master/src/main/java/net/opentsdb/tsd/KafkaRpcPluginGroup.java#L132) and [then instantiates the Deserialiser](https://github.com/OpenTSDB/opentsdb-rpc-kafka/blob/master/src/main/java/net/opentsdb/tsd/KafkaRpcPluginGroup.java#L138), the reference to the deserialiser in the thread object is null. This reference is never updated which is eventually causing a null pointer exception when the first message comes in. 

I think the creation of the threads should happen after the deserialiser is initialised.

**Comment by mancubus77** [comment]
@muffix mate, have you fixed the issue? Any luck with getting messages from kafka queue? I was playing around this plugin, but was not able to run it because of serialisation issue.
Cheers

-

**Comment by muffix** [comment]
With the changes from #11 it works for me.

**Comment by mancubus77** [comment]
__

**Comment by muffix** [comment]
Yours looks like a completely different issue @mancubus77. It can't find the class `net.opentsdb.rollup.RollUpDataPoint` which is part of OpenTSDB 2.4. The version in the dependencies (`2.4.0-20170603.203549-1`) has that class, so it's probably worth checking that. To keep this issue free from unrelated discussion, would you mind creating a separate issue if you still think your problem isn't in your code/setup?

**Comment by mancubus77** [comment]
You right mate, sorry

**Comment by mancubus77** [comment]
Just want to confirm #1 + @muffix suggestions works fine with 2.4.0RC2
